name: Build & Test
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - LICENSE
      - ".github/**/*"
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - README.md
      - LICENSE
      - ".github/**/*"
jobs:
  run:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17

      - name: Validate Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.minecraft/assets
            .gradle
            build/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/1.20.1' }}

      - name: Build
        run: chmod u+x ./gradlew && ./gradlew build

      - name: Test JAR with GameTest Server
        run: ./gradlew runGameTestServer
        timeout-minutes: 20
        env:
          CM_RELEASE: false
          CM_SEMVER_VERSION: ${{ needs.vars.outputs.version }}
          CM_BUILD_NUM: ${{ needs.vars.outputs.build }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-data
          path: run/gametest
